### ISSUE TITLE
How to use observer (API?)

### ISSUE THREAD

**Issue by spanzetta** [home-assistant/plugin-observer#150]
I wonder if it's possible to use the Observer (trough port 4357) for sending command to HA instance (in my case running on RPI) to force a restart or to download logs..
I see in the Readme page that it mentions 2 Api command but it is not clear how to use them .. and I noticed that a /restart command was available in the past but apparently it is now removed.. 

I have sometimes my RPI tha doesn't respond on 8123 port (main GUI), even with local IP, but the Observer is running and it reports connected and healthy.. so my idea was to use it to restart the Raspberry.. but I need instructions (I don't keep SSH enabled for security)

I think that this can be usefull to all users in the same situation

**Comment by spanzetta** [comment]
Nobody can help?

**Comment by jjvelar** [comment]
I am interested too!

**Comment by agners** [comment]
> I wonder if it's possible to use the Observer (trough port 4357) for sending command to HA instance (in my case running on RPI) to force a restart or to download logs..

The logs are shared, e.g. you can query them through `http://ha-yellow-prod.lan:4357/logs`. However, there is no full fledged API, as the observer has no authentication.
