### ISSUE TITLE
Watchdog/Application found a problem with observer plugin!

### ISSUE THREAD

**Issue by egor-romanko** [home-assistant/plugin-observer#22]
Hello,

I've noticed some weird behavior of my Home Assistant instance that decided to check the logs. It turned out that the Observer plugin fails many times per day and it seems it also affect other addons (like mosquitto) sometimes.

Home Assistant is running on Raspberry PI 3 with 32Gb SD card:

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.5
supervisor | 2020.12.6
timezone | Europe/Minsk
version | 0.116.4
virtualenv | false

The issue in the logs always look like this:

> 
> 20-12-10 16:38:03 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!
> 20-12-10 16:38:09 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping hassio_observer application
> 20-12-10 16:38:38 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-mosquitto with version 5.1
> 20-12-10 16:38:55 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning hassio_observer application
> 20-12-10 16:38:56 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
> 20-12-10 16:38:59 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
> 20-12-10 16:39:32 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'ha'
> 20-12-10 16:39:35 INFO (MainThread) [supervisor.auth] Successful login for 'ha'
> 20-12-10 16:39:56 INFO (SyncWorker_7) [supervisor.docker.observer] Starting Observer homeassistant/armv7-hassio-observer with version 2020.10.1 - 172.30.32.6
> 20-12-10 16:42:34 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
> 20-12-10 16:42:34 INFO (MainThread) [supervisor.resolution.check] System checks complete

Could you help to fix this issue, please?

**Comment by bcutter** [comment]
Yap that occurs sometimes. :-( https://github.com/home-assistant/operating-system/issues/1119#issuecomment-753516171

```
21-01-02 18:51:44 WARNING (MainThread) [supervisor.misc.tasks] Watchdog/Application found a problem with observer plugin!
21-01-02 18:53:28 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping hassio_observer application
21-01-02 18:54:16 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning hassio_observer application
21-01-02 18:54:33 INFO (MainThread) [supervisor.plugins.observer] Starting observer plugin
21-01-02 18:56:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-01-02 18:57:45 INFO (SyncWorker_6) [supervisor.docker.observer] Starting Observer homeassistant/aarch64-hassio-observer with version 2020.10.1 - 172.XX.XX.X
```

In my case at the same time when whole system is about to freeze.

**Comment by ludeeus** [comment]
Timeout has been increased in the supervisorr
