### ISSUE TITLE
Running clean install supervised, with error installing Observer?

### ISSUE THREAD

**Issue by ranrinc** [home-assistant/plugin-observer#45]
I got this error on portainer when installing the HA

```
21-06-15 12:07:24 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/amd64-hassio-observer with tag 2020.10.1.

21-06-15 12:07:25 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/amd64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Famd64-hassio-observer: Internal Server Error ("name unknown")
```

Any help?

**Comment by PvaI** [comment]
the docker pull command fails with a 'name unknown'.

enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.1
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.1.
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.0
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:3
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:latest
latest: Pulling from home-assistant/aarch64-hassio-observer
Digest: sha256:c205e173fcc187ea9ac0abf4202ef9bd8d0376834294f07fa878418cb1903dc5
Status: Downloaded newer image for ghcr.io/home-assistant/aarch64-hassio-observer:latest
ghcr.io/home-assistant/aarch64-hassio-observer:latest

supervisor logs:
Starting local supervisor watchdog...
21-06-15 12:54:23 INFO (MainThread) [__main__] Initializing Supervisor setup
21-06-15 12:54:23 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-06-15 12:54:23 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: odroid-n2
21-06-15 12:54:23 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2021.06.0
21-06-15 12:54:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-06-15 12:54:23 WARNING (MainThread) [supervisor.resolution.evaluations.base] AppArmor is required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/apparmor)
21-06-15 12:54:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-15 12:54:23 INFO (MainThread) [__main__] Setting up Supervisor
21-06-15 12:54:23 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-06-15 12:54:23 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
21-06-15 12:54:29 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
21-06-15 12:54:29 INFO (MainThread) [supervisor.host.info] Updating local host information
21-06-15 12:54:29 INFO (MainThread) [supervisor.host.services] Updating service information
21-06-15 12:54:30 INFO (MainThread) [supervisor.host.network] Updating local network information
21-06-15 12:54:30 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-06-15 12:54:30 INFO (MainThread) [supervisor.host] Host information reload completed
21-06-15 12:54:30 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-06-15 12:54:30 INFO (MainThread) [supervisor.host.services] Reloading local service hassio-apparmor.service
21-06-15 12:54:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0
21-06-15 12:54:30 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
21-06-15 12:54:30 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_dns application
21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0 - 172.30.32.3
21-06-15 12:54:31 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0
21-06-15 12:54:31 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_audio application
21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0 - 172.30.32.4
21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1
21-06-15 12:54:32 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_cli application
21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1 - 172.30.32.5
21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for homeassistant/aarch64-hassio-observer
21-06-15 12:54:33 INFO (MainThread) [supervisor.plugins.observer] No observer plugin Docker image homeassistant/aarch64-hassio-observer found.
21-06-15 12:54:33 INFO (MainThread) [supervisor.plugins.observer] Running setup for observer plugin
21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
21-06-15 12:54:34 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
21-06-15 12:54:34 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec
21-06-15 12:55:03 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
21-06-15 12:55:04 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
21-06-15 12:55:04 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec

**Comment by ranrinc** [comment]
> the docker pull command fails with a 'name unknown'.
> 
> enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.1 Error response from daemon: name unknown enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.1.
> Error response from daemon: name unknown
> enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2010.10.0 Error response from daemon: name unknown enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:3
> Error response from daemon: name unknown
> enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:latest
> latest: Pulling from home-assistant/aarch64-hassio-observer
> Digest: sha256:c205e173fcc187ea9ac0abf4202ef9bd8d0376834294f07fa878418cb1903dc5
> Status: Downloaded newer image for ghcr.io/home-assistant/aarch64-hassio-observer:latest
> ghcr.io/home-assistant/aarch64-hassio-observer:latest
> 
> supervisor logs:
> Starting local supervisor watchdog...
> 21-06-15 12:54:23 INFO (MainThread) [**main**] Initializing Supervisor setup
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: odroid-n2
> 21-06-15 12:54:23 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2021.06.0
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
> 21-06-15 12:54:23 WARNING (MainThread) [supervisor.resolution.evaluations.base] AppArmor is required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/apparmor)
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
> 21-06-15 12:54:23 INFO (MainThread) [**main**] Setting up Supervisor
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
> 21-06-15 12:54:23 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
> 21-06-15 12:54:29 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
> 21-06-15 12:54:29 INFO (MainThread) [supervisor.host.info] Updating local host information
> 21-06-15 12:54:29 INFO (MainThread) [supervisor.host.services] Updating service information
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.host.network] Updating local network information
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.host] Host information reload completed
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.host.services] Reloading local service hassio-apparmor.service
> 21-06-15 12:54:30 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0
> 21-06-15 12:54:30 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
> 21-06-15 12:54:30 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_dns application
> 21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0 - 172.30.32.3
> 21-06-15 12:54:31 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
> 21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0
> 21-06-15 12:54:31 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
> 21-06-15 12:54:31 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_audio application
> 21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0 - 172.30.32.4
> 21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1
> 21-06-15 12:54:32 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
> 21-06-15 12:54:32 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_cli application
> 21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1 - 172.30.32.5
> 21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for homeassistant/aarch64-hassio-observer
> 21-06-15 12:54:33 INFO (MainThread) [supervisor.plugins.observer] No observer plugin Docker image homeassistant/aarch64-hassio-observer found.
> 21-06-15 12:54:33 INFO (MainThread) [supervisor.plugins.observer] Running setup for observer plugin
> 21-06-15 12:54:33 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
> 21-06-15 12:54:34 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
> 21-06-15 12:54:34 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec
> 21-06-15 12:55:03 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
> 21-06-15 12:55:04 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
> 21-06-15 12:55:04 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec

is it working if you pull the latest version?

**Comment by PvaI** [comment]
No, supervisor keeps trying to get 2020.10.1

The :latest tag seems to download 2021.04.dev1301, which is also downloadable via docker pull <...> :2021.04.dev1301

Not sure why it shows 2010 above, re-ran commands to verify: 

enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.0
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:3
Error response from daemon: name unknown
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2021.04.dev1301
2021.04.dev1301: Pulling from home-assistant/aarch64-hassio-observer
Digest: sha256:c205e173fcc187ea9ac0abf4202ef9bd8d0376834294f07fa878418cb1903dc5
Status: Image is up to date for ghcr.io/home-assistant/aarch64-hassio-observer:2021.04.dev1301
ghcr.io/home-assistant/aarch64-hassio-observer:2021.04.dev1301

**Comment by ranrinc** [comment]
Something is wrong.. Supervised unable to find the files. Somehow that version is being deleted?

**Comment by PvaI** [comment]
how would I be able to download from a host missing a toplevel domain? -> homeassistant

`"cli": "ghcr.io/home-assistant/{arch}-hassio-cli",    "audio": "ghcr.io/home-assistant/{arch}-hassio-audio",    "dns": "ghcr.io/home-assistant/{arch}-hassio-dns",    "observer": "ghcr.io/home-assistant/{arch}-hassio-observer",    "observer": "homeassistant/{arch}-hassio-observer",    "multicast": "ghcr.io/home-assistant/{arch}-hassio-multicast"`

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/plugin-observer/pkgs/container/amd64-hassio-observer> <https://version.home-assistant.io/stable.json>
The correct version is now available on ghcr.io as well.

**Comment by PvaI** [comment]
could it be stuff is cached somewhere or am I missing something?

enduser@HomeAssistant:~$ rm installer.sh 
enduser@HomeAssistant:~$ ps -ef|grep hass
enduser       3041    2983  0 12:13 pts/0    00:00:00 grep --color=auto hass
enduser@HomeAssistant:~$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
enduser@HomeAssistant:~$ curl -Lo installer.sh https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8536  100  8536    0     0  38624      0 --:--:-- --:--:-- --:--:-- 38800
enduser@HomeAssistant:~$ bash installer.sh --machine odroid-n2
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
[info] Creating NetworkManager configuration
[warn] Changes are needed to the /etc/network/interfaces file
[info] If you have modified the network on the host manualy, those can now be overwritten
[info] If you do not overwrite this now you need to manually adjust it later
[info] Do you want to proceed with overwriting the /etc/network/interfaces file? [N/y] 
y
[info] Replacing /etc/network/interfaces
[info] Restarting NetworkManager
[info] Install supervisor Docker container
[info] Install supervisor startup scripts
[info] Install AppArmor scripts
[info] Start Home Assistant Supervised
[info] Installing the 'ha' cli
[info] 
[info] Home Assistant supervised is now installed
[info] First setup will take some time, when it's ready you can reach it here:
[info] http://10.0.0.7:8123
[info] 
enduser@HomeAssistant:~$ docker ps
CONTAINER ID   IMAGE                                     COMMAND   CREATED         STATUS         PORTS     NAMES
232ad7c3046e   homeassistant/aarch64-hassio-supervisor   "/init"   3 seconds ago   Up 2 seconds             hassio_supervisor
enduser@HomeAssistant:~$ docker logs 232ad7c3046e
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[11:26:08] INFO: Using udev information from host
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:26:08] INFO: Starting local supervisor watchdog...
21-06-16 11:26:10 INFO (MainThread) [__main__] Initializing Supervisor setup
21-06-16 11:26:10 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
21-06-16 11:26:10 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: odroid-n2
21-06-16 11:26:10 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2021.06.0
21-06-16 11:26:10 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connecting Supervisor to hassio-network
21-06-16 11:26:10 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
21-06-16 11:26:10 WARNING (MainThread) [supervisor.resolution.evaluations.base] AppArmor is required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/apparmor)
21-06-16 11:26:10 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-16 11:26:10 INFO (MainThread) [__main__] Setting up Supervisor
21-06-16 11:26:10 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
21-06-16 11:26:10 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
21-06-16 11:26:16 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
21-06-16 11:26:16 INFO (MainThread) [supervisor.host.info] Updating local host information
21-06-16 11:26:16 INFO (MainThread) [supervisor.host.services] Updating service information
21-06-16 11:26:16 INFO (MainThread) [supervisor.host.network] Updating local network information
21-06-16 11:26:17 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-06-16 11:26:17 INFO (MainThread) [supervisor.host] Host information reload completed
21-06-16 11:26:17 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
21-06-16 11:26:17 INFO (MainThread) [supervisor.host.services] Reloading local service hassio-apparmor.service
21-06-16 11:26:17 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0
21-06-16 11:26:17 INFO (MainThread) [supervisor.plugins.dns] Starting CoreDNS plugin
21-06-16 11:26:17 INFO (SyncWorker_0) [supervisor.docker.dns] Starting DNS ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0 - 172.30.32.3
21-06-16 11:26:17 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
21-06-16 11:26:17 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0
21-06-16 11:26:17 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-06-16 11:26:18 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.04.0 - 172.30.32.4
21-06-16 11:26:18 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1
21-06-16 11:26:18 INFO (MainThread) [supervisor.plugins.cli] Starting CLI plugin
21-06-16 11:26:19 INFO (SyncWorker_0) [supervisor.docker.cli] Starting CLI ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.05.1 - 172.30.32.5
21-06-16 11:26:19 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for homeassistant/aarch64-hassio-observer
21-06-16 11:26:19 INFO (MainThread) [supervisor.plugins.observer] No observer plugin Docker image homeassistant/aarch64-hassio-observer found.
21-06-16 11:26:19 INFO (MainThread) [supervisor.plugins.observer] Running setup for observer plugin
21-06-16 11:26:19 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
21-06-16 11:26:20 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
21-06-16 11:26:20 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec
21-06-16 11:26:50 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/aarch64-hassio-observer with tag 2020.10.1.
21-06-16 11:26:50 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2020.10.1&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-observer: Internal Server Error ("name unknown")
21-06-16 11:26:50 WARNING (MainThread) [supervisor.plugins.observer] Error on install observer plugin. Retry in 30sec
enduser@HomeAssistant:~$ docker images
REPOSITORY                                       TAG         IMAGE ID       CREATED        SIZE
ghcr.io/home-assistant/aarch64-hassio-observer   2021.06.0   03599d665b8e   21 hours ago   96.9MB
ghcr.io/home-assistant/aarch64-hassio-dns        2021.06.0   905e97a60aaf   28 hours ago   104MB
homeassistant/aarch64-hassio-supervisor          2021.06.0   faf8c58a2a99   5 days ago     326MB
homeassistant/aarch64-hassio-supervisor          latest      faf8c58a2a99   5 days ago     326MB
ghcr.io/home-assistant/aarch64-hassio-cli        2021.05.1   61a50d0fe057   2 weeks ago    97.5MB
ghcr.io/home-assistant/aarch64-hassio-audio      2021.04.0   f3026526922b   6 weeks ago    111MB
enduser@HomeAssistant:~$ docker pull ghcr.io/home-assistant/aarch64-hassio-observer:2020.10.1
Error response from daemon: name unknown
